const users = [


    
  { id: 1, name: "Manav", age: 20 },
  { id: 2, name: "Rahul", age: 22 },
  { id: 3, name: "Priya", age: 19 },
  { id: 4, name: "Amit", age: 25 },
  { id: 5, name: "Sneha", age: 21 },
  { id: 6, name: "Rohan", age: 23 },
  { id: 7, name: "Neha", age: 24 },
  { id: 8, name: "Arjun", age: 22 },
  { id: 9, name: "Kavya", age: 20 },
  { id: 10, name: "Vikram", age: 26 },
  { id: 11, name: "Anjali", age: 23 },
  { id: 12, name: "Suresh", age: 28 },
  { id: 13, name: "Pooja", age: 21 },
  { id: 14, name: "Karan", age: 24 },
  { id: 15, name: "Meena", age: 22 },
  { id: 16, name: "Deepak", age: 27 },
  { id: 17, name: "Nisha", age: 20 },
  { id: 18, name: "Harsh", age: 23 },
  { id: 19, name: "Ritika", age: 22 },
  { id: 20, name: "Yash", age: 21 },
  { id: 21, name: "Tanvi", age: 19 },
  { id: 22, name: "Aditya", age: 24 },
  { id: 23, name: "Simran", age: 23 },
  { id: 24, name: "Varun", age: 25 },
  { id: 25, name: "Isha", age: 20 },
  { id: 26, name: "Akash", age: 26 },
  { id: 27, name: "Payal", age: 22 },
  { id: 28, name: "Mohit", age: 23 },
  { id: 29, name: "Divya", age: 21 },
  { id: 30, name: "Sahil", age: 24 },
  { id: 31, name: "Komal", age: 20 },
  { id: 32, name: "Rakesh", age: 27 },
  { id: 33, name: "Shreya", age: 22 },
  { id: 34, name: "Nitin", age: 25 },
  { id: 35, name: "Preeti", age: 21 },
  { id: 36, name: "Abhishek", age: 26 },
  { id: 37, name: "Ayesha", age: 23 },
  { id: 38, name: "Gaurav", age: 24 },
  { id: 39, name: "Sonia", age: 22 },
  { id: 40, name: "Ravi", age: 28 },
  { id: 41, name: "Juhi", age: 20 },
  { id: 42, name: "Ankit", age: 23 },
  { id: 43, name: "Tanya", age: 21 },
  { id: 44, name: "Kunal", age: 25 },
  { id: 45, name: "Bhavna", age: 22 },
  { id: 46, name: "Raj", age: 26 },
  { id: 47, name: "Seema", age: 24 },
  { id: 48, name: "Naveen", age: 27 },
  { id: 49, name: "Muskan", age: 20 },
  { id: 50, name: "Lokesh", age: 23 },
  { id: 51, name: "Pankaj", age: 25 },
  { id: 52, name: "Ritu", age: 22 },
  { id: 53, name: "Vikas", age: 26 },
  { id: 54, name: "Saloni", age: 21 },
  { id: 55, name: "Hemant", age: 24 },
  { id: 56, name: "Alok", age: 27 },
  { id: 57, name: "Swati", age: 23 },
  { id: 58, name: "Chirag", age: 25 },
  { id: 59, name: "Pallavi", age: 22 },
  { id: 60, name: "Rohit", age: 24 }
];

export default users;